name: Run ADO to GitHub Sync with Python

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      # - name: Setup Python
      #   uses: actions/setup-python@v5.0.0
      #   with:
      #     # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
      #     python-version: 3.9
      #     # File containing the Python version to use. Example: .python-version
      - run: |
             python test.py -GitHubDestinationPAT ${{ secrets.GITHUBDESTINATIONPAT }} -ADOSourcePAT ${{ secrets.ADOSOURCEPAT }} -AzureRepoName $($object.AzureRepoName)  -ADOCloneURL $($object.ADOCloneURL)  -GitHubCloneURL  $($object.GitHubCloneURL)
